### ISSUE TITLE
Enhancement: optional features designed as workarounds when a timeout is detected

### ISSUE THREAD

**Issue by wabetainfo** [OllieJones/sqlite-object-cache#40]
I wanted to suggest some optional features that the user could activate in case they experience random timeouts caused by the plugin.

1. Direct query to the MariaDB database: if, for any reason, the database created by the plugin becomes inaccessible or locked due to a process, this optional feature temporarily enables direct querying of the MariaDB database. This is intended to avoid the website staying inaccessible while waiting for the database generated by the plugin to be unlocked.
2. Automatic deactivation and reactivation: this optional feature would restart the object caching system when some timeouts are detected. The database generated by the plugin and object-cache.php are then deleted, and the plugin is restarted after a few minutes, regenerating the database and object-cache.php, so that the process causing the timeout can be halted. Based on my experience, when my website becomes inaccessible due to this plugin, I immediately delete the database, object-cache.php, and I disable the plugin, resolving the issue instantly. Then, I reactivate the plugin.

I understand that these features may seem aggressive, that's why they are marked as optional, allowing the user to decide whether to activate them or not. In case you disagree, I would appreciate it if you could explore alternative optional features designated as workarounds. I understand that debugging this issue is very complicated due to the limited information available. As a result, I believe implementing new features that operate in these moments could be beneficial for users who frequently encounter timeouts on their websites. As always, thanks for your efforts to make this plugin better!

**Comment by OllieJones** [comment]
Back in June I added some  code which forces SQLite3 to checkpoint its writeahead log in a synchronous fashion once in a while. See this:  https://www.plumislandmedia.net/reference/sqlite3-in-php-some-notes/#checkpointing-the-write-ahead-log  I think the timeouts were occurring on busy sites where the cache never got enough idle time to do its checkpointing normally.

I haven't had any reports of timeouts since then. So I guess the problem is solved. (Of course, maybe users have just given up in disgust ... but w.org's reports of the active users keeps going up.
